; Generated by Zeal 8-bit C Compiler
; Target: Z80

    org 0x4000

; Program code
main:
    ld a, 2
    push af
    ld a, 3
    push af
    ld a, 4
    ld l, a
    pop af
; Multiplication (A * L)
    call __mul_a_l
    ld l, a
    pop af
    add a, l
    ret


; Runtime library functions

__mul_a_l:
    ld b, 0
    or a
    ret z
__mul_loop:
    add a, b
    ld b, a
    dec l
    ret z
    ld a, b
    jr __mul_loop

__div_a_l:
    ld b, 0
    ld c, a
__div_loop:
    ld a, c
    cp l
    ret c
    sub l
    ld c, a
    inc b
    jr __div_loop

__mod_a_l:
    call __div_a_l
    ld a, c
    ret
