; Generated by Zeal 8-bit C Compiler
; Target: Z80

    org 0x4000

; Program code
add:
; Load variable: 
; a
    ld a, (a)
    push af
; Load variable: 
; b
    ld a, (b)
    ld l, a
    pop af
    add a, l
    ret

main:
; Variable: 
; x
x:
    defb 0
; Variable: 
; y
y:
    defb 0
    ld a, 5
    ld (x), a
    ld a, 10
    ld (y), a
; Call function: 
; add
    call add
    ret


; Runtime library functions

__mul_a_l:
    ld b, 0
    or a
    ret z
__mul_loop:
    add a, b
    ld b, a
    dec l
    ret z
    ld a, b
    jr __mul_loop

__div_a_l:
    ld b, 0
    ld c, a
__div_loop:
    ld a, c
    cp l
    ret c
    sub l
    ld c, a
    inc b
    jr __div_loop

__mod_a_l:
    call __div_a_l
    ld a, c
    ret
