; Generated by Zeal 8-bit C Compiler
; Target: Z80

    org 0x4000

; Program code
main:
; Variable: 
; x
x:
    defb 0
    ld a, 5
    ld (x), a
; Load variable: 
; x
    ld a, (x)
    push af
    ld a, 5
    ld l, a
    pop af
; Equality test (A == L)
    cp l
    ld a, 0
    jr nz, $+3
    ld a, 1
    or a
    jp z, L0
    ld a, 42
    ret
L0:
    ld a, 0
    ret


; Runtime library functions

__mul_a_l:
    ld b, 0
    or a
    ret z
__mul_loop:
    add a, b
    ld b, a
    dec l
    ret z
    ld a, b
    jr __mul_loop

__div_a_l:
    ld b, 0
    ld c, a
__div_loop:
    ld a, c
    cp l
    ret c
    sub l
    ld c, a
    inc b
    jr __div_loop

__mod_a_l:
    call __div_a_l
    ld a, c
    ret
