; Generated by Zeal 8-bit C Compiler
; Target: Z80

    org 0x4000

; Program code
main:
; Variable: 
; x
x:
    defb 0
; Variable: 
; sum
sum:
    defb 0
    ld a, 0
    ld (x), a
    ld a, 0
    ld (sum), a
L0:
; Load variable: 
; x
    ld a, (x)
    push af
    ld a, 5
    ld l, a
    pop af
; Less than test (A < L)
    cp l
    ld a, 0
    jr nc, $+3
    ld a, 1
    or a
    jp z, L1
; Load variable: 
; sum
    ld a, (sum)
    push af
; Load variable: 
; x
    ld a, (x)
    ld l, a
    pop af
    add a, l
    ld (sum), a
; Load variable: 
; x
    ld a, (x)
    push af
    ld a, 1
    ld l, a
    pop af
    add a, l
    ld (x), a
    jp L0
L1:
; Load variable: 
; sum
    ld a, (sum)
    ret


; Runtime library functions

__mul_a_l:
    ld b, 0
    or a
    ret z
__mul_loop:
    add a, b
    ld b, a
    dec l
    ret z
    ld a, b
    jr __mul_loop

__div_a_l:
    ld b, 0
    ld c, a
__div_loop:
    ld a, c
    cp l
    ret c
    sub l
    ld c, a
    inc b
    jr __div_loop

__mod_a_l:
    call __div_a_l
    ld a, c
    ret
